services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  HauerHeinrich\HhExtFilesize\:
    resource: '../Classes/*'

  HauerHeinrich\HhExtFilesize\Controller\Backend\FileSizeModuleController:
    tags: ['backend.controller']
